// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_fused_add_rms_norm` namespace so the task
// can call torch.ops.extracted_fused_add_rms_norm.fused_add_rms_norm without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void fused_add_rms_norm(torch::Tensor& input, torch::Tensor& residual, torch::Tensor& weight, double epsilon);

TORCH_LIBRARY(extracted_fused_add_rms_norm, m) {
    m.def("fused_add_rms_norm(Tensor! input, Tensor! residual, Tensor weight, float epsilon) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_fused_add_rms_norm, CUDA, m) {
    m.impl("fused_add_rms_norm", &fused_add_rms_norm);
}
