// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_paged_attention` namespace so the task
// can call torch.ops.extracted_paged_attention.paged_attention without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void paged_attention( torch::Tensor& out, torch::Tensor& exp_sums, torch::Tensor& max_logits, torch::Tensor& tmp_out, torch::Tensor& query, torch::Tensor& key_cache, torch::Tensor& value_cache, int64_t num_kv_heads, double scale, torch::Tensor& block_tables, torch::Tensor& seq_lens, const std::optional<torch::Tensor>& query_start_loc, int64_t block_size, int64_t max_seq_len, const std::optional<torch::Tensor>& alibi_slopes, const std::string& kv_cache_dtype, torch::Tensor& k_scale, torch::Tensor& v_scale, const std::optional<torch::Tensor>& fp8_out_scale, const std::string& mfma_type);

TORCH_LIBRARY(extracted_paged_attention, m) {
    m.def("paged_attention(Tensor! out, Tensor exp_sums,                Tensor max_logits, Tensor tmp_out,                Tensor query, Tensor key_cache,                Tensor value_cache, int num_kv_heads,                float scale, Tensor block_tables,                Tensor seq_lens,                Tensor? query_start_loc,                int block_size,                int max_seq_len,                Tensor? alibi_slopes,                str kv_cache_dtype,                Tensor k_scale, Tensor v_scale,                Tensor? fp8_out_scale,                str mfma_type) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_paged_attention, CUDA, m) {
    m.impl("paged_attention", &paged_attention);
}
