
#!/usr/bin/env python3
"""Generate a lazy EvoK rebind shim + wire it into an e2e overlay.

Produces  <overlay>/evok_shim_<tag>.py  and registers a rebind entry via overlay_setup.py.

WHY a generated shim instead of `overlay_setup.py --impl-file <evok entry>`:
  (a) --impl-file copies ONE file; EvoK's gemm impl loads four sibling modules relative to
      __file__ (_decode_tiled / _prefill_configs / _splitk_decode / _v_vllm_shim). Copying
      the entry alone breaks on the first sibling import.
  (b) evok.resolve() already does the sys.path work (backend_dir + extra_pythonpath +
      _engine/pylibs + _engine/shims) under _NoBytecode(). Re-deriving it here would drift.
  (c) sitecustomize runs at INTERPRETER STARTUP. A module-level resolve() would import torch
      and JIT triton in every python process the server spawns. The shim must be LAZY.

The shim also carries a CALL COUNTER dumped at exit -> the engagement proof the
e2e_integrator gate requires BEFORE the timed A/B.

Usage:
  python3 evok_overlay_shim.py --overlay <dir> --hit <evok_hit.json>
                               --live-seam <module:attr> [--tag gemm] [--counter-out <path>]
"""
import argparse, json, os, subprocess, sys

TEMPLATE = '''# AUTO-GENERATED by evok_overlay_shim.py — do not edit; regenerate instead.
# Lazy EvoK rebind shim. Module import MUST stay side-effect free: sitecustomize imports
# this at interpreter startup in EVERY python process the server spawns.
import atexit, os, sys, threading

_EVOK_LIB       = {evok_lib!r}
_RESOLVE_KEY    = {resolve_key!r}
_REGIME         = {regime!r}
_DTYPE          = {dtype!r}
_SHAPE_SET      = {shape_set!r}
_GFX            = {gfx!r}
_FORM           = {form!r}
_COUNTER_OUT    = {counter_out!r}

_fn = None
_lock = threading.Lock()
_calls = 0


def _tick():
    """CALL marker, emitted PROGRESSIVELY (1, 10, 100, ...), not only at atexit.

    The integrator must be able to reject a non-engaging overlay in MINUTES, while the server is
    still up — an atexit-only counter forces it to tear the server down first. Format follows the
    contract in roles/e2e_integrator.md §4: '[evok-*] CALLS ...<n>' with a growing n.
    """
    global _calls
    _calls += 1
    if _calls in (1, 10, 100, 1000, 10000, 100000):
        sys.stderr.write("[evok-shim] CALLS %s=%d pid=%d\\n"
                         % (_RESOLVE_KEY, _calls, os.getpid()))
        sys.stderr.flush()


def _get():
    """Resolve on FIRST CALL (not at import): keeps interpreter startup free of torch/triton."""
    global _fn
    if _fn is None:
        with _lock:
            if _fn is None:
                if _EVOK_LIB and _EVOK_LIB not in sys.path:
                    sys.path.insert(0, _EVOK_LIB)
                if _GFX:
                    os.environ.setdefault("EVOK_GFX", _GFX)
                import evok
                f = evok.resolve(_RESOLVE_KEY, regime=_REGIME, dtype=_DTYPE,
                                 shape_set=(_SHAPE_SET or None), gfx=(_GFX or None))
                if f is None:
                    raise RuntimeError("evok.resolve(%r) returned None inside the live server"
                                       % (_RESOLVE_KEY,))
                # BIND marker, in the shared contract vocabulary (see roles/e2e_integrator.md §4):
                #   [evok-*] rebound|resolved <seam-or-key> -> <module>.<attr>
                sys.stderr.write("[evok-shim] resolved %s -> %s.%s\\n"
                                 % (_RESOLVE_KEY, f.__module__, f.__name__))
                _fn = f
    return _fn


@atexit.register
def _dump():
    """Engagement proof. The integrator reads this BEFORE trusting any timed A/B:
    ref leg must show 0, candidate leg must show >0."""
    msg = "[evok-shim] CALLS %s=%d\\n" % (_RESOLVE_KEY, _calls)
    sys.stderr.write(msg)
    if _COUNTER_OUT:
        try:
            with open(_COUNTER_OUT, "a") as fh:
                fh.write("%d %s pid=%d\\n" % (_calls, _RESOLVE_KEY, os.getpid()))
        except Exception:
            pass


{body}
'''

# One body per signature form. The shim's OWN signature must match the LIVE SEAM it replaces;
# the body then re-orders arguments into whatever EvoK's entry wants. Pure reordering — no
# reshape, no transpose, no dtype cast. The scale layouts already agree (see evok_lookup.py).
BODIES = {
    # live seam: vllm fp8_utils:w8a8_triton_block_scaled_mm  (EvoK entry is the SAME form)
    "vllm6": '''
def w8a8_triton_block_scaled_mm(A, B, As, Bs, block_size, output_dtype=None):
    _tick()
    import torch
    return _get()(A, B, As, Bs, block_size, output_dtype or torch.bfloat16)
''',
    # live seam: sglang fp8_utils:apply_w8a8_block_fp8_linear-style 5-arg form,
    # EvoK entry is the vLLM 6-arg form -> reorder + supply block_size positionally.
    "sglang5_to_vllm6": '''
def apply_w8a8_block_fp8_linear(x, w, x_scale, w_scale, dtype=None, block_size=None):
    _tick()
    import torch
    return _get()(x, w, x_scale, w_scale, list(block_size or [128, 128]),
                  dtype or torch.bfloat16)
''',
    "dense3": '''
def gemm(x, w, bias=None):
    _tick()
    out = _get()(x, w, None)
    return out if bias is None else out + bias
''',
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--overlay", required=True)
    ap.add_argument("--hit", required=True, help="evok_hit.json from evok_lookup.py")
    ap.add_argument("--live-seam", required=True, dest="live_seam",
                    help="module:attr in the LIVE engine to rebind (NOT EvoK's declared seam "
                         "unless they coincide — the live backend decides)")
    ap.add_argument("--form", default="", help="override the shim body form")
    ap.add_argument("--tag", default="evok")
    ap.add_argument("--counter-out", default="", dest="counter_out")
    a = ap.parse_args()

    with open(a.hit) as fh:
        hit = json.load(fh)
    if not hit.get("hit"):
        raise SystemExit("evok_hit.json is a miss: %s" % hit.get("reason"))
    if not hit.get("deployable"):
        raise SystemExit("EvoK impl is NOT deployable: %s" % hit.get("reason"))

    form = a.form or hit.get("signature_form") or ""
    if form not in BODIES:
        raise SystemExit("no shim body for signature_form=%r (have %s)" % (form, sorted(BODIES)))

    os.makedirs(a.overlay, exist_ok=True)
    modname = "evok_shim_%s" % a.tag
    path = os.path.join(a.overlay, modname + ".py")
    with open(path, "w") as fh:
        fh.write(TEMPLATE.format(
            evok_lib=hit["evok_pythonpath"], resolve_key=hit["resolve_key"],
            regime=hit.get("regime", "decode"), dtype=hit.get("dtype", ""),
            shape_set=hit.get("shape_set", ""), gfx=hit.get("gfx", ""),
            form=form, counter_out=a.counter_out, body=BODIES[form]))

    impl_attr = BODIES[form].strip().split("(")[0].split()[-1]
    setup = os.path.join(os.path.dirname(os.path.abspath(__file__)), "overlay_setup.py")
    subprocess.run([sys.executable, setup, "add-rebind", "--overlay", a.overlay,
                    "--target", a.live_seam, "--impl-module", modname,
                    "--impl-attr", impl_attr], check=True)

    print(json.dumps({
        "shim": path, "impl_module": modname, "impl_attr": impl_attr,
        "target": a.live_seam, "form": form,
        "pythonpath": "%s:%s" % (a.overlay, hit["evok_pythonpath"]),
        # The marker CONTRACT is route-agnostic (roles/e2e_integrator.md §4). This script's own
        # literal is reported for convenience, but the gate must grep the class, not this string —
        # a hand-written overlay tags itself differently and would otherwise read as no_engagement.
        "engagement_marker": "[evok-shim] CALLS %s=" % hit["resolve_key"],
        "engagement_grep_bind": r"\[evok-[a-z]+\] (rebound|resolved) ",
        "engagement_grep_call": r"\[evok-[a-z]+\] CALLS .*[0-9]+",
    }, indent=2))


if __name__ == "__main__":
    main()
