#!/usr/bin/env python3
"""E2E-layer per-task empirical roofline driver.

WHY THIS EXISTS
---------------
The recursive single-kernel workflow (kernel_workflow) is the ONLY place the empirical
roofline collector (kernel_workflow/scripts/roofline_kernel.py) was wired. But a large
class of e2e wins never enter that recursion: a head/config win applied via the
env-lever + source-overlay track (backend switch, e.g. Triton->CK, plus aiter gemm
autotuning) is gated purely on e2e throughput A/B and produces NO roofline. So an
extracted hot kernel could be optimized end-to-end yet never get a single roofline
reading of how much hardware headroom remains.

This driver closes that gap at the e2e layer WITHOUT modifying the immutable per-task
scaffold and WITHOUT reimplementing any roofline logic: it REUSES roofline_kernel.py.
Given a frozen task dir (the standalone unittest bundle produced by kernel_extractor:
meta.json + workload cases + unittest.py + harness_lib.py) it

  1. selects representative workload cases (highest-weight + one per serving regime),
  2. writes a candidate-only single-shape profiling driver that loads the task's
     IMMUTABLE unittest.py to reuse its frozen synth + harness + callable resolution
     (baseline phase profiles the frozen baseline callable; post phase profiles the
     accepted candidate, selected via GEAK_GEMM_CANDIDATE + any accepted env),
  3. builds a roofline manifest and runs `roofline_kernel.py collect`,
  4. on the 'post' phase also runs `roofline_kernel.py compare` against the baseline
     collection to quantify the before/after roofline delta.

Everything is FAIL-SOFT: roofline_kernel.py itself returns a structured "skipped" report
when rocprof-compute is unavailable, and any error here is reported as status=error and
never raises into the caller (roofline is a diagnostic, never a gate).

USAGE
-----
  roofline_task.py --task-dir DIR --phase baseline --gpu-id 0
  roofline_task.py --task-dir DIR --phase post --gpu-id 0 \
      --candidate-spec aiter:gemm_a8w8_blockscale \
      --env "AITER_CONFIG_GEMM_A8W8_BLOCKSCALE=/path/tuned.csv AITER_LOG_TUNED_CONFIG=1" \
      --kernel-pattern "Cijk_.*"

Prints a compact one-line summary JSON on stdout.
"""
import argparse
import json
import os
import re
import shlex
import subprocess
import sys


DRIVER_SOURCE = r'''#!/usr/bin/env python3
"""AUTO-GENERATED by roofline_task.py -- do not edit.

Thin, CONTRACT-ANCHORED roofline launcher. It does NOT reach into the unittest's private,
agent-authored glue (no _build_correctness / _current_call / _eager_cases). Instead it runs the
task's IMMUTABLE unittest.py under its OWN main() with GEAK_ROOFLINE_SIG set, so the SHARED harness
-- harness_lib.run_correctness(), the ONE entrypoint every conforming unittest is required to call
(kernel_extractor contract) -- short-circuits into a candidate-only, single-case tight loop that
rocprof-compute attributes to the deployed kernel. Because the contract is the harness (immutable +
sha-checked) and not the agent's function names, this works for GEMM and attention heads alike and
does not drift when the unittest template changes.

Candidate selection is the unittest's OWN job (its module-level code reads META["current_callable_env"]).
For the baseline phase no candidate env is set => the frozen baseline resolves. For the post phase
roofline_task.py exports the accepted candidate as GEAK_GEMM_CANDIDATE; we bridge that into the env
var name THIS task actually reads -- discovered generically from the sibling meta.json
(current_callable_env), with the known names as fallback -- BEFORE the unittest module loads.
"""
import argparse
import json
import os
import runpy
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--unittest", required=True)
    ap.add_argument("--sig", required=True)   # carries the workload case NAME
    ap.add_argument("--warmup", type=int, default=8)
    ap.add_argument("--iters", type=int, default=40)
    args = ap.parse_args()

    # Arm the harness roofline hook (read inside run_correctness).
    os.environ["GEAK_ROOFLINE_SIG"] = args.sig
    os.environ["GEAK_ROOFLINE_WARMUP"] = str(args.warmup)
    os.environ["GEAK_ROOFLINE_ITERS"] = str(args.iters)

    # Bridge the accepted candidate (post phase) into the env var name this task reads. Keyed on
    # the STABLE contract file (meta.json), not on hardcoded names; no-op for the baseline phase.
    cand = os.environ.get("GEAK_GEMM_CANDIDATE") or os.environ.get("GEAK_CANDIDATE_CALLABLE")
    if cand:
        env_names = {"GEAK_GEMM_CANDIDATE", "GEAK_CANDIDATE_CALLABLE", "CURRENT_GEMM_CALLABLE"}
        meta_path = os.path.join(os.path.dirname(os.path.abspath(args.unittest)), "meta.json")
        try:
            with open(meta_path, encoding="utf-8") as handle:
                declared = (json.load(handle) or {}).get("current_callable_env")
            if declared:
                env_names.add(declared)
        except (OSError, ValueError):
            pass
        for name in env_names:
            os.environ[name] = cand

    # Run the unittest's real main(): its module setup unshadows stdlib `unittest` and resolves the
    # (now-bridged) candidate; run_correctness sees GEAK_ROOFLINE_SIG and sys.exit()s after the tight
    # loop, BEFORE any baseline/correctness/timing work -- so the profile is candidate-only.
    runpy.run_path(args.unittest, run_name="__main__")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


def _default_roofline_script():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(
        os.path.join(here, "..", "..", "kernel_workflow", "scripts", "roofline_kernel.py")
    )


def _default_install_script():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(
        os.path.join(here, "..", "..", "kernel_workflow", "scripts", "install_rocprof_compute.sh")
    )


def _ensure_rocprof_compute(install_mode, install_script, out_dir, env, timeout_sec):
    """Mandatory install step of the roofline flow: reuse the kernel-layer
    install_rocprof_compute.sh to detect-then-install rocprof-compute before we collect.

    Returns (ok, info) where info is a dict merged into the result. The installer is
    idempotent (it detects an existing runnable tool first), so calling it once per task
    is a fast no-op when the profiler is already present. `install_mode`:
      - "off":      skip the step entirely (only when roofline itself is disabled)
      - "auto":     always run the installer; fail-soft (never blocks collection)
      - "required": run the installer with --required; a non-runnable tool is fatal
    """
    info = {"install_status": "skipped", "install_reason": "", "install_json": ""}
    if install_mode == "off":
        info["install_reason"] = "install mode=off"
        return True, info
    if not install_script or not os.path.isfile(install_script):
        info["install_status"] = "unavailable"
        info["install_reason"] = "install_rocprof_compute.sh not found at %s" % install_script
        # Missing installer is only fatal under "required".
        return (install_mode != "required"), info

    install_json = os.path.join(out_dir, "install.json")
    cmd = ["bash", install_script, "--install", "--json-out", install_json]
    if install_mode == "required":
        cmd.append("--required")
    code, output = _run(cmd, env, timeout_sec=min(timeout_sec, 1800.0))
    log_path = os.path.join(out_dir, "install.log")
    try:
        with open(log_path, "w", encoding="utf-8") as handle:
            handle.write(output)
    except OSError:
        pass
    if os.path.isfile(install_json):
        info["install_json"] = install_json
        try:
            with open(install_json, "r", encoding="utf-8") as handle:
                payload = json.load(handle)
            info["install_status"] = payload.get("status") or ("ok" if code == 0 else "failed")
            info["install_reason"] = payload.get("reason") or ""
        except Exception:  # noqa: BLE001
            info["install_status"] = "ok" if code == 0 else "failed"
    else:
        info["install_status"] = "ok" if code == 0 else "failed"
        info["install_reason"] = output.strip()[-200:]
    ok = (code == 0) if install_mode == "required" else True
    return ok, info


def _load_meta(task_dir):
    with open(os.path.join(task_dir, "meta.json"), "r", encoding="utf-8") as handle:
        return json.load(handle)


def _case_id(case):
    """Stable per-case identifier. The immutable unittest keys its workload cases by
    `name` (for GEMM and attention heads alike, e.g. down_proj_decode_M1 / prefill_s512);
    a legacy `sig` key is honored as a fallback for older extracted task dirs."""
    return case.get("name") or case.get("sig")


def _select_cases(meta, max_cases):
    """Representative case selection (mirrors benchmark_engineer.md ordering):
    one highest-weight case per serving regime first (decode/prefill coverage), then fill
    by descending weight up to max_cases. Dedup by case id. Op-shape-agnostic: cases are
    identified by their `name` (not a GEMM-only `sig`), so non-GEMM heads (attention) are
    selected too."""
    cases = ((meta.get("workload") or {}).get("cases")) or []
    cases = [c for c in cases if isinstance(c, dict) and _case_id(c)]
    if not cases:
        return []
    ranked = sorted(cases, key=lambda c: -(float(c.get("weight") or 0.0)))
    picked, seen_id, seen_regime = [], set(), set()
    # one highest-weight case per serving regime first (decode/prefill coverage)
    for c in ranked:
        regime = c.get("regime")
        if regime in seen_regime:
            continue
        seen_regime.add(regime)
        cid = _case_id(c)
        if cid not in seen_id:
            picked.append(c)
            seen_id.add(cid)
    # then fill by weight
    for c in ranked:
        if len(picked) >= max_cases:
            break
        cid = _case_id(c)
        if cid not in seen_id:
            picked.append(c)
            seen_id.add(cid)
    return picked[:max_cases]


def _case_shape(case):
    """Best-effort GEMM M/N/K for manifest metadata ONLY (never required downstream:
    roofline_kernel derives FLOP/AI from rocprof counters + dtypes, not shape). Emitted
    only for genuine GEMM cases, identified by explicit scalar M/N/K keys; returns None
    for non-GEMM cases (e.g. attention, which carry seqlen_q/seqlen_kv and 3-D q/k/v
    `dims` but no scalar N/K) so no misleading shape is recorded for them."""
    if case.get("N") is None or case.get("K") is None or case.get("m") is None:
        return None
    try:
        return {"M": int(case["m"]), "N": int(case["N"]), "K": int(case["K"])}
    except (TypeError, ValueError):
        return None


def _build_manifest(meta, task_dir, driver_path, unittest_path, cases, gpu_id, patterns,
                    exclude_patterns=()):
    exclude_patterns = list(exclude_patterns or [])
    target = {
        "logical_name": meta.get("short_name") or "kernel",
        "gpu_id": str(gpu_id) if gpu_id is not None and str(gpu_id).strip() != "" else None,
        "kernel_patterns": patterns,
        "exclude_patterns": exclude_patterns,
        "op_kind": meta.get("op_kind", ""),
    }
    manifest_cases = []
    for c in cases:
        cid = _case_id(c)
        entry = {
            "case_id": cid,
            "command": [sys.executable, driver_path, "--unittest", unittest_path, "--sig", cid],
            "workdir": task_dir,
            "dtypes": c.get("dtypes") or [],
            "regime": c.get("regime", ""),
            "weight": c.get("weight"),
            "kernel_patterns": patterns,
            "exclude_patterns": exclude_patterns,
        }
        shape = _case_shape(c)   # GEMM only; attention omits it (metadata, not required)
        if shape is not None:
            entry["shape"] = shape
        manifest_cases.append(entry)
    return {"schema_version": 1, "target": target, "cases": manifest_cases}


def _baseline_exclude_patterns(baseline_report_path):
    """Literal-regex excludes derived from the baseline's matched kernel symbols.

    In post phase a config/backend swap deploys a DIFFERENT callable. The harness
    roofline hook runs the CANDIDATE only (it sys.exit()s before any baseline work),
    so the baseline kernel should no longer leak; but as belt-and-suspenders against
    any residual baseline kernel from module setup -- being one big kernel vs the
    swapped backend's many smaller kernels it could still win the duration-ranked
    fallback -- we read the baseline's matched kernel name(s) and hand them to the
    collector as
    exclude_patterns so the DEPLOYED kernel is selected instead. rocprof-compute
    may truncate the reported symbol (trailing '...'), so we strip that and use
    the surviving prefix as a literal substring regex (re.search matches it inside
    the full device symbol). Returns [] on any issue (fail-soft)."""
    try:
        with open(baseline_report_path, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return []
    names = set()
    for case in (data.get("cases") or []):
        name = (case.get("matched_kernel_name") or "").strip()
        name = name.rstrip(". ").strip()   # drop rocprof's trailing '...'/spaces
        if len(name) >= 8:                 # ignore too-short/ambiguous fragments
            names.add(name)
    return [re.escape(n) for n in sorted(names)]


def _run(cmd, env, timeout_sec):
    try:
        completed = subprocess.run(
            cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            universal_newlines=True, check=False, timeout=timeout_sec,
        )
        return completed.returncode, completed.stdout or ""
    except subprocess.TimeoutExpired as error:
        return 124, (error.stdout or "") + "\nroofline_task: collect timed out\n"
    except OSError as error:
        return 127, "roofline_task: %s\n" % error


def _summary_from_report(report_path):
    """Pull a compact classification/utilization summary out of a phase report."""
    out = {"dominant_classification": "", "pct_of_peak": None}
    try:
        with open(report_path, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except Exception:
        return out
    summary = data.get("summary") or {}
    cls = summary.get("dominant_classification") or {}
    if isinstance(cls, dict):
        out["dominant_classification"] = cls.get("bound") or cls.get("classification") or ""
    elif isinstance(cls, str):
        out["dominant_classification"] = cls
    for key in ("dominant_pct_of_peak", "pct_of_peak", "achieved_pct_of_peak"):
        val = summary.get(key)
        if isinstance(val, (int, float)):
            out["pct_of_peak"] = float(val)
            break
    out["status"] = data.get("status", "")
    out["reason"] = data.get("reason", "")
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--task-dir", required=True)
    ap.add_argument("--phase", required=True, choices=["baseline", "post"])
    ap.add_argument("--out-dir", default=None, help="default <task-dir>/roofline")
    ap.add_argument("--gpu-id", default=os.environ.get("HIP_VISIBLE_DEVICES", "0"))
    ap.add_argument("--roofline-script", default=None)
    ap.add_argument("--roofline-mode", default="auto", choices=["off", "auto", "required"])
    ap.add_argument("--roofline-install", default="auto", choices=["off", "auto", "required"],
                    help="mandatory install step: auto=always run installer (fail-soft), "
                         "required=fail if rocprof-compute not runnable after install, off=skip")
    ap.add_argument("--install-script", default=None,
                    help="path to install_rocprof_compute.sh (defaults next to roofline_kernel.py)")
    ap.add_argument("--max-cases", type=int, default=3)
    ap.add_argument("--timeout-sec", type=float, default=1200.0)
    ap.add_argument("--saturation-pct", type=float, default=60.0)
    ap.add_argument("--candidate-spec", default="", help="post: mod:attr -> GEAK_GEMM_CANDIDATE")
    ap.add_argument("--kernel-pattern", default="", help="extra regex; post winner kernel symbol")
    ap.add_argument("--env", default="", help='space-separated "K=V" pairs exported to case commands')
    ap.add_argument("--baseline-report", default=None, help="post: baseline_roofline.json for compare")
    ap.add_argument("--dry-run", action="store_true", help="build manifest+driver, skip profiling")
    args = ap.parse_args(argv)

    result = {"status": "error", "phase": args.phase, "task_dir": args.task_dir,
              "report_path": "", "compare_path": "", "note": ""}

    if args.roofline_mode == "off":
        result.update(status="skipped", note="roofline mode=off")
        print(json.dumps(result))
        return 0

    task_dir = os.path.abspath(args.task_dir)
    unittest_path = os.path.join(task_dir, "unittest.py")
    if not os.path.isfile(os.path.join(task_dir, "meta.json")) or not os.path.isfile(unittest_path):
        result["note"] = "task_dir missing meta.json/unittest.py"
        print(json.dumps(result))
        return 0

    try:
        meta = _load_meta(task_dir)
    except Exception as error:  # noqa: BLE001
        result["note"] = "could not read meta.json: %s" % error
        print(json.dumps(result))
        return 0

    out_dir = os.path.abspath(args.out_dir or os.path.join(task_dir, "roofline"))
    os.makedirs(out_dir, exist_ok=True)

    cases = _select_cases(meta, max(1, args.max_cases))
    if not cases:
        result.update(status="skipped", note="no representative workload cases in meta")
        print(json.dumps(result))
        return 0

    # candidate-only driver reused for both phases (env selects which callable CURRENT is)
    driver_path = os.path.join(out_dir, "roofline_driver.py")
    with open(driver_path, "w", encoding="utf-8") as handle:
        handle.write(DRIVER_SOURCE)

    name_match = ((meta.get("workload") or {}).get("name_match")) or ""
    exclude_patterns = []
    if args.phase == "baseline":
        patterns = [p for p in [name_match] if p]
    else:
        # post: prefer an explicit winner symbol; else profile the dominant kernel the
        # candidate-only driver runs (patterns=[] => roofline_kernel picks the top kernel).
        patterns = [p for p in [args.kernel_pattern] if p]
        # Backend/config swap: --candidate-spec deploys a DIFFERENT callable than the frozen
        # baseline. The harness hook runs candidate-only, but as belt-and-suspenders we still
        # exclude the baseline's matched kernel from the duration-ranked fallback so the DEPLOYED
        # kernel is selected (no manual --kernel-pattern needed). Skipped when an explicit pattern
        # was given (it already pins the winner) or when no
        # candidate-spec is set (we're profiling the frozen callable itself).
        if args.candidate_spec and not patterns:
            baseline_report = args.baseline_report or os.path.join(out_dir, "baseline_roofline.json")
            exclude_patterns = _baseline_exclude_patterns(baseline_report)

    manifest = _build_manifest(meta, task_dir, driver_path, unittest_path, cases, args.gpu_id, patterns,
                               exclude_patterns=exclude_patterns)
    manifest_path = os.path.join(out_dir, "manifest_%s.json" % args.phase)
    with open(manifest_path, "w", encoding="utf-8") as handle:
        json.dump(manifest, handle, indent=2, sort_keys=True)

    report_path = os.path.join(out_dir, "%s_roofline.json" % args.phase)
    result["report_path"] = report_path
    result["manifest_path"] = manifest_path

    if args.dry_run:
        result.update(status="dry_run", note="manifest+driver built; profiling skipped",
                      cases=[_case_id(c) for c in cases], kernel_patterns=patterns,
                      exclude_patterns=exclude_patterns)
        print(json.dumps(result))
        return 0

    roofline_script = args.roofline_script or _default_roofline_script()
    if not os.path.isfile(roofline_script):
        result["note"] = "roofline_kernel.py not found at %s" % roofline_script
        if args.roofline_mode == "required":
            print(json.dumps(result))
            return 2
        result["status"] = "skipped"
        print(json.dumps(result))
        return 0

    # env for case commands: os.environ + selected GPU + accepted env + candidate switch
    env = os.environ.copy()
    if str(args.gpu_id).strip():
        env["HIP_VISIBLE_DEVICES"] = str(args.gpu_id)
        env["ROCR_VISIBLE_DEVICES"] = str(args.gpu_id)
    if args.phase == "post" and args.candidate_spec.strip():
        env["GEAK_GEMM_CANDIDATE"] = args.candidate_spec.strip()
    for pair in shlex.split(args.env or ""):
        if "=" in pair:
            key, _, value = pair.partition("=")
            if key.strip():
                env[key.strip()] = value

    # Mandatory install step of the roofline flow: ensure rocprof-compute is present
    # (idempotent detect-then-install) before collecting. Honors --roofline-install.
    install_script = args.install_script or _default_install_script()
    install_ok, install_info = _ensure_rocprof_compute(
        args.roofline_install, install_script, out_dir, env, args.timeout_sec)
    result.update(install_info)
    if not install_ok and args.roofline_install == "required":
        result["note"] = "rocprof-compute install required but failed: %s" % install_info.get(
            "install_reason", "")
        print(json.dumps(result))
        return 2

    collect_cmd = [
        sys.executable, roofline_script, "collect",
        "--manifest", manifest_path, "--phase", args.phase, "--out-dir", out_dir,
        "--timeout-sec", str(args.timeout_sec), "--saturation-pct", str(args.saturation_pct),
    ]
    code, output = _run(collect_cmd, env, timeout_sec=args.timeout_sec + 120.0)
    log_path = os.path.join(out_dir, "%s_collect.log" % args.phase)
    try:
        with open(log_path, "w", encoding="utf-8") as handle:
            handle.write(output)
    except OSError:
        pass

    if not os.path.isfile(report_path):
        result["note"] = "collect produced no report (exit=%d); see %s" % (code, log_path)
        if args.roofline_mode == "required":
            print(json.dumps(result))
            return 2
        result["status"] = "skipped"
        print(json.dumps(result))
        return 0

    summary = _summary_from_report(report_path)
    result["status"] = summary.get("status") or "collected"
    result["dominant_classification"] = summary.get("dominant_classification", "")
    result["pct_of_peak"] = summary.get("pct_of_peak")
    if summary.get("reason"):
        result["note"] = summary["reason"]

    # post: compare against the baseline collection when present
    if args.phase == "post":
        before = args.baseline_report or os.path.join(out_dir, "baseline_roofline.json")
        if os.path.isfile(before):
            compare_path = os.path.join(out_dir, "compare.json")
            cmp_cmd = [sys.executable, roofline_script, "compare",
                       "--before", before, "--after", report_path, "--out", compare_path]
            ccode, coutput = _run(cmp_cmd, env, timeout_sec=180.0)
            if os.path.isfile(compare_path):
                result["compare_path"] = compare_path
            else:
                result["note"] = (result.get("note") or "") + \
                    " | compare failed (exit=%d): %s" % (ccode, coutput.strip()[-200:])
        else:
            result["note"] = (result.get("note") or "") + " | no baseline_roofline.json to compare"

    print(json.dumps(result))
    return 0


if __name__ == "__main__":
    sys.exit(main())
