#!/usr/bin/env python3
"""Read, validate and RENDER the per-SKU peak table -- perf_knowledge/hardware/data/sku.json.

A GEAK shared kernel tool (kernel_workflow/scripts/kernel_tools/; the Gluon pack keeps a shim at
scripts/extract_sku.py). The direction of this tool is now the reverse of what its name used to
mean: sku.json is THE single per-SKU source (hand-edited, sourced per row), calc_perf.SKU_PEAKS is
READ from it, and every markdown copy of its numbers is DERIVED from it here. Nothing writes
sku.json any more -- the old generator dumped it from calc_perf's hard-coded dict, which made two
transcriptions of one datasheet that a correction could reach on one side only.

    extract_sku.py --print MI355X              # one row (read-only)
    extract_sku.py --check                     # schema + cross-row invariants of sku.json
    extract_sku.py --render peaks-yaml         # the e2e roofline peaks.md yaml blocks
    extract_sku.py --render table gfx950,gfx942
    extract_sku.py --check-docs                # every GENERATED block in the docs == a fresh render
    extract_sku.py --sync-docs                 # rewrite those blocks in place (after editing sku.json)
    extract_sku.py --selftest

A doc opts in by wrapping a block in
    <!-- BEGIN GENERATED by extract_sku.py: <kind> [args] -->
    ...
    <!-- END GENERATED by extract_sku.py -->
(kinds: `peaks-yaml`, `table <arch>[,<arch>...]`, `table all`). --check-docs scans the markdown
under e2e_workflow/knowledge, kernel_workflow/knowledge, perf_knowledge/hardware and the Gluon
pack's references/hardware.

The ridge is NOT stored and not rendered as data: it is peak_tflops[dtype]/peak_hbm_tb_s, valid
only at the dtype it was taken at; use ridge_for(row, dtype), which returns None for a dtype the
row does not list (no fp16 fallback).
"""
from __future__ import annotations

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)
import _hwdata  # noqa: E402

REPO_ROOT = str(_hwdata.REPO_ROOT)
DOC_DIRS = ("e2e_workflow/knowledge", "kernel_workflow/knowledge", "perf_knowledge/hardware",
            "perf_knowledge/profiling", "perf_knowledge/optimization",
            "perf_knowledge/expert_skills/skills/gluon_authoring/references/hardware")
BEGIN_RE = re.compile(r"^<!-- BEGIN GENERATED by extract_sku\.py: (.+?) -->\s*$", re.M)
END_MARK = "<!-- END GENERATED by extract_sku.py -->"

COMPUTE_BASES = ("datasheet", "derived", "orc-derived")
HBM_BASES = ("datasheet", "measured", "orc-derived")
DTYPE_COLS = ("fp16", "fp8", "fp4", "int8", "fp32", "fp64")
MIB = 1 << 20


def load(path=None) -> dict:
    p = path or _hwdata.find("sku.json")
    if not p:
        raise SystemExit("extract_sku: sku.json not found ($GEAK_HW_DATA_DIR or "
                         "perf_knowledge/hardware/data)")
    with open(p) as fh:
        return json.load(fh)


def _is_rdna(arch: str) -> bool:
    """True/False from hw_constants' family field. STOPS if the family cannot be established --
    never "assume CDNA", which would accept a per-CU LDS figure on an RDNA part (see _lds_doc)."""
    fam = ((_hwdata.load_json("hw_constants.json").get("arch") or {}).get(arch) or {}).get("family")
    if not fam:
        raise SystemExit(f"extract_sku: hw_constants.json has no family for arch {arch!r}, so this "
                         f"tool cannot tell whether lds_per_cu_kib is a real quantity for it.")
    return str(fam).upper().startswith("RDNA")


def ridge_for(row: dict, dtype: str = "fp16"):
    """peak_tflops[dtype] / peak_hbm_tb_s, computed per call; None if the dtype has no rate."""
    pk = (row.get("peak_tflops") or {}).get(dtype)
    bw = row.get("peak_hbm_tb_s")
    return round(pk / bw, 1) if (pk and bw) else None


def hbm_datasheet_tb_s(row: dict) -> float:
    """The pin-rate (datasheet) external-memory bandwidth -- what a rank-only roofline divides by."""
    return row.get("datasheet_hbm_tb_s") or row["peak_hbm_tb_s"]


# --------------------------------------------------------------------------- invariants

def check(doc: dict) -> list:
    """Every problem with sku.json as a list of strings ([] = clean)."""
    bad = []
    skus = doc.get("skus") or {}
    if not skus:
        return ["no skus"]
    names = list(skus)
    # gfx950 is the main line: its rows come first
    first_non950 = next((i for i, n in enumerate(names) if skus[n]["arch"] != "gfx950"), len(names))
    if any(skus[n]["arch"] == "gfx950" for n in names[first_non950:]):
        bad.append("row order: every gfx950 row must precede every other row")
    defaults = {}
    for name, r in skus.items():
        tag = f"{name}:"
        for f in ("arch", "cus", "peak_hbm_tb_s", "peak_tflops", "basis", "peak_hbm_basis",
                  "source", "geak_support", "wave_size", "vgpr_per_simd", "vgpr_per_wave"):
            if r.get(f) in (None, "", {}):
                bad.append(f"{tag} missing {f}")
        if "ridge_ops_per_byte" in r:
            bad.append(f"{tag} stores a derived ridge (see _no_derived_ridge)")
        if r.get("basis") not in COMPUTE_BASES:
            bad.append(f"{tag} basis {r.get('basis')!r} not in {COMPUTE_BASES}")
        if r.get("basis") == "derived" and not r.get("basis_note"):
            bad.append(f"{tag} basis=derived needs basis_note")
        if r.get("peak_hbm_basis") not in HBM_BASES:
            bad.append(f"{tag} peak_hbm_basis {r.get('peak_hbm_basis')!r} not in {HBM_BASES}")
        if r.get("peak_hbm_basis") == "measured":
            if not r.get("datasheet_hbm_tb_s"):
                bad.append(f"{tag} measured HBM without datasheet_hbm_tb_s")
            if not any(m.get("metric") == "hbm_tb_s" and m.get("tool") and m.get("tool_version")
                       for m in r.get("measured_ceilings") or []):
                bad.append(f"{tag} measured HBM without a measured_ceilings entry naming tool + version")
        for m in r.get("measured_ceilings") or []:
            for f in ("metric", "value", "tool", "tool_version", "source"):
                if m.get(f) in (None, ""):
                    bad.append(f"{tag} measured_ceilings entry missing {f}: {m}")
        pk = r.get("peak_tflops") or {}
        if "fp16" not in pk:
            bad.append(f"{tag} no fp16 rate")
        for dt, tf in pk.items():
            if not (isinstance(tf, (int, float)) and tf > 0):
                bad.append(f"{tag} peak_tflops.{dt}={tf!r} (an absent rate is absent, not zero)")
        if "bf16" in pk and pk.get("bf16") != pk.get("fp16"):
            bad.append(f"{tag} bf16 != fp16 (same matrix-core rate on every tabulated part)")
        if r.get("geak_support") not in ("supported", "unsupported"):
            bad.append(f"{tag} geak_support {r.get('geak_support')!r}")
        if r.get("arch") in ("gfx1100", "gfx1200") and r.get("geak_support") != "unsupported":
            bad.append(f"{tag} {r['arch']} rows are kept for reference only (geak_support=unsupported)")
        if r.get("roofline_default_for_arch"):
            if r.get("geak_support") != "supported":
                bad.append(f"{tag} an unsupported row cannot be an arch default")
            if r["arch"] in defaults:
                bad.append(f"{tag} second arch default for {r['arch']} ({defaults[r['arch']]})")
            defaults[r["arch"]] = name
        if r.get("xcds") and r.get("l2_per_xcd_mb") and r.get("l2_mb") != r["xcds"] * r["l2_per_xcd_mb"]:
            bad.append(f"{tag} l2_mb != xcds x l2_per_xcd_mb")
        try:
            rdna = _is_rdna(r["arch"])
        except SystemExit as e:
            bad.append(f"{tag} {e}")
            continue
        if rdna and r.get("lds_per_cu_kib") is not None:
            bad.append(f"{tag} RDNA row carries a per-CU LDS figure (see _lds_doc)")
        if not rdna and not r.get("lds_per_cu_kib"):
            bad.append(f"{tag} CDNA row lost its per-CU LDS pool")
        if r.get("vgpr_per_wave", 0) > r.get("vgpr_per_simd", 0):
            bad.append(f"{tag} vgpr_per_wave > vgpr_per_simd")
    if "gfx1201" in defaults:
        bad.append("gfx1201 has an arch default: R9700 peaks are product-scoped")
    # per-arch dtype:fp16 ratio is fixed (same CU design; clock and CU count cancel)
    by_arch = {}
    for name, r in skus.items():
        by_arch.setdefault(r["arch"], []).append((name, r))
    for arch, members in by_arch.items():
        for dt in sorted({d for _, r in members for d in r["peak_tflops"]} - {"fp16"}):
            ratios = [(n, r["peak_tflops"][dt] / r["peak_tflops"]["fp16"])
                      for n, r in members if dt in r["peak_tflops"] and r["peak_tflops"].get("fp16")]
            if len(ratios) >= 2:
                lo, hi = min(x for _, x in ratios), max(x for _, x in ratios)
                if (hi - lo) / hi >= 0.02:
                    bad.append(f"{arch}: {dt}:fp16 ratio varies across SKUs {ratios}")
    targets = [r.get("identity_target") for r in skus.values() if r.get("identity_target")]
    if len(targets) != len(set(targets)):
        bad.append(f"duplicate identity_target in {targets}")
    return bad


# --------------------------------------------------------------------------- renderers

def _num(x):
    return "%.6g" % x


def peaks_entry(name: str, row: dict) -> dict:
    """The e2e roofline view of one row (what roofline_tools.load_peaks returns, minus provenance
    fields). Memory is the DATASHEET pin rate: the e2e roofline ranks against datasheet ceilings
    and carries the measured R9700/gfx1151 figures separately (target_eff / measured_ceilings)."""
    l2 = row.get("l2_per_xcd_mb") or row.get("l2_mb")
    return {
        "gfx": row["arch"], "sku": name, "cu": row["cus"],
        "hbm_bw_bytes_s": hbm_datasheet_tb_s(row) * 1e12,
        "flops": {dt: tf * 1e12 for dt, tf in row["peak_tflops"].items()},
        "l2_bytes": int(l2 * MIB) if l2 else None,
        "mall_bytes": int(row["mall_mb"] * MIB) if row.get("mall_mb") else None,
        "basis": row["basis"],
    }


def roofline_rows(doc: dict):
    """(name, row) the e2e roofline can reach: supported AND (product identity OR arch default)."""
    for name, r in doc["skus"].items():
        if r.get("geak_support") == "supported" and (r.get("identity_target")
                                                     or r.get("roofline_default_for_arch")):
            yield name, r


def render_peaks_yaml(doc: dict) -> str:
    out = []
    for name, r in roofline_rows(doc):
        e = peaks_entry(name, r)
        scope = []
        if r.get("roofline_default_for_arch"):
            scope.append(f"the default for a bare `{r['arch']}`")
        if r.get("identity_target"):
            scope.append(f"selected by `product: {r['identity_target']}`")
        out.append(f"### {name} — {r.get('product') or name} ({r['arch']}, {r['family']}); "
                   + " and ".join(scope))
        out.append("```yaml")
        if r.get("identity_target"):
            out.append(f"product: {r['identity_target']}")
        out.append(f"gfx: {r['arch']}")
        out.append(f"sku: {name}")
        if r.get("roofline_default_for_arch"):
            out.append("default_for_gfx: true")
        out.append(f"cu: {e['cu']}")
        hb = f"{r['peak_hbm_basis']}" if r["peak_hbm_basis"] == "datasheet" else \
            f"datasheet pin rate; sku.json peak_hbm_tb_s {r['peak_hbm_tb_s']} is {r['peak_hbm_basis']}"
        out.append(f"hbm_bw_bytes_s: {_num(e['hbm_bw_bytes_s'])}    # {hb}")
        out.append("flops:                          # dense, FLOP/s (OPS/s for int)")
        for dt, v in e["flops"].items():
            out.append(f"  {dt}: {_num(v)}")
        if e["l2_bytes"]:
            out.append(f"l2_bytes: {e['l2_bytes']}" + ("    # per XCD" if r.get("l2_per_xcd_mb") else ""))
        if e["mall_bytes"]:
            out.append(f"mall_bytes: {e['mall_bytes']}")
        out.append(f"basis: {r['basis']}")
        out.append("```")
        out.append("")
    return "\n".join(out).rstrip("\n")


def _tf(x):
    if x is None:
        return "—"
    return ("%.1f" % x).rstrip("0").rstrip(".") if x < 1000 else "%g" % x


_CLK = {"peak_engine": "peak", "gpu_boost": "boost"}


def render_table(doc: dict, archs) -> str:
    rows = [(n, r) for n, r in doc["skus"].items() if archs == "all" or r["arch"] in archs]
    head = ("| SKU | arch | CUs | clock (MHz) | mem BW TB/s | L2 / MALL (MB) | FP16 = BF16 | FP8 | "
            "FP4 | INT8 | FP32 | FP64 | basis | GEAK |")
    out = [head, "| " + " | ".join(["---"] * 14) + " |"]
    for n, r in rows:
        pk, vec = r["peak_tflops"], r.get("peak_tflops_vector") or {}
        clk = r.get("clock_mhz") or {}
        clock = " / ".join(f"{_CLK.get(k, k)} {v}" for k, v in clk.items()) if clk else "—"
        bw = "%g" % r["peak_hbm_tb_s"]
        if r["peak_hbm_basis"] != "datasheet":
            bw += f" {r['peak_hbm_basis']}"
            if r.get("datasheet_hbm_tb_s"):
                bw += " (%g datasheet)" % r["datasheet_hbm_tb_s"]
        cache = f"{r.get('l2_mb') or '—'} / {r.get('mall_mb') or '—'}"
        cells = []
        for dt in DTYPE_COLS:
            v = pk.get(dt)
            c = _tf(v)
            if dt in ("fp32", "fp64") and vec.get(dt) is not None and vec[dt] != v:
                c += f" (vec {_tf(vec[dt])})"
            cells.append(c)
        out.append(f"| {n} | {r['arch']} | {r['cus']} | {clock} | {bw} | {cache} | "
                   + " | ".join(cells) + f" | {r['basis']} | "
                   + ("yes" if r["geak_support"] == "supported" else "reference only") + " |")
    out.append("")
    out.append("Dense TFLOP/s (TOPS for INT8), no sparsity; `—` = no rate on record (a consumer "
               "refuses, never substitutes FP16). Generated from `perf_knowledge/hardware/data/sku.json` "
               "by `kernel_workflow/scripts/kernel_tools/extract_sku.py`; edit the json, then "
               "`extract_sku.py --sync-docs`.")
    return "\n".join(out)


def render(doc: dict, spec: str) -> str:
    parts = spec.split()
    if parts[0] == "peaks-yaml":
        return render_peaks_yaml(doc)
    if parts[0] == "table":
        arg = parts[1] if len(parts) > 1 else "all"
        return render_table(doc, "all" if arg == "all" else tuple(arg.split(",")))
    raise SystemExit(f"extract_sku: unknown render kind {spec!r}")


# --------------------------------------------------------------------------- doc blocks

def _blocks(text: str):
    for m in BEGIN_RE.finditer(text):
        end = text.find(END_MARK, m.end())
        if end < 0:
            yield m.group(1), m.end(), None
            continue
        yield m.group(1), m.end(), end


def doc_files(root=REPO_ROOT):
    for d in DOC_DIRS:
        base = os.path.join(root, d)
        for dp, _dn, fns in os.walk(base):
            for fn in sorted(fns):
                if fn.endswith(".md"):
                    p = os.path.join(dp, fn)
                    with open(p, encoding="utf-8") as fh:
                        if "BEGIN GENERATED by extract_sku.py" in fh.read():
                            yield p


def check_docs(doc: dict, files=None) -> list:
    bad = []
    for p in (files if files is not None else list(doc_files())):
        text = open(p, encoding="utf-8").read()
        for spec, start, end in _blocks(text):
            if end is None:
                bad.append(f"{p}: block {spec!r} has no END marker")
                continue
            have = text[start:end].strip("\n")
            want = render(doc, spec).strip("\n")
            if have != want:
                bad.append(f"{p}: generated block {spec!r} is stale -- run extract_sku.py --sync-docs")
    return bad


def sync_docs(doc: dict, files=None) -> list:
    changed = []
    for p in (files if files is not None else list(doc_files())):
        text = open(p, encoding="utf-8").read()
        out, pos = [], 0
        for spec, start, end in _blocks(text):
            if end is None:
                raise SystemExit(f"{p}: block {spec!r} has no END marker")
            out.append(text[pos:start])
            out.append("\n" + render(doc, spec).strip("\n") + "\n")
            pos = end
        out.append(text[pos:])
        new = "".join(out)
        if new != text:
            with open(p, "w", encoding="utf-8") as fh:
                fh.write(new)
            changed.append(p)
    return changed


# --------------------------------------------------------------------------- selftest

def _selftest() -> int:
    import copy
    import tempfile
    d = load()
    problems = check(d)
    assert not problems, "sku.json invariants:\n  " + "\n  ".join(problems)
    s = d["skus"]
    # the decided numbers (sku.json is the single source; every md table must agree)
    want = {
        "MI355X": dict(fp16=2500.0, fp8=5000.0, fp4=10000.0, fp32=157.3, fp64=78.6, hbm=8.0, cus=256),
        "MI350X": dict(fp16=2300.0, fp8=4600.0, fp4=9200.0, fp32=144.2, hbm=8.0, cus=256),
        "MI300X": dict(fp16=1307.4, fp8=2614.9, fp32=163.4, hbm=5.3, cus=304),
        "MI325X": dict(fp16=1307.4, fp8=2614.9, fp32=163.4, hbm=6.0, cus=304),
    }
    for name, w in want.items():
        r = s[name]
        assert r["cus"] == w.pop("cus") and r["peak_hbm_tb_s"] == w.pop("hbm"), name
        for dt, v in w.items():
            assert r["peak_tflops"][dt] == v, (name, dt, r["peak_tflops"].get(dt), v)
        assert r["peak_tflops"]["bf16"] == r["peak_tflops"]["fp16"], name
    assert s["MI350X"]["clock_mhz"] != s["MI355X"]["clock_mhz"], "MI350X and MI355X clocks differ"
    g = s["AI_MAX_395"]
    assert (g["peak_hbm_tb_s"], g["peak_hbm_basis"], g["datasheet_hbm_tb_s"]) == (0.212, "measured", 0.256)
    assert (g["l2_mb"], g["mall_mb"]) == (2, 32), (g["l2_mb"], g["mall_mb"])
    for n, r in s.items():
        if r["arch"] in ("gfx1100", "gfx1200"):
            assert r["geak_support"] == "unsupported", n
    # ridge: computed, per dtype, None for an absent dtype (never the fp16 one)
    assert abs(ridge_for(s["MI300X"]) - 246.7) < 1.0, ridge_for(s["MI300X"])
    assert ridge_for(s["MI300X"], "fp4") is None
    assert ridge_for(s["MI355X"], "fp4") == 1250.0
    # the checker FIRES on each defect it exists for (not only passes on a clean file)
    for mutate, needle in (
            (lambda x: x["skus"]["MI355X"]["peak_tflops"].__setitem__("bf16", 2400.0), "bf16 != fp16"),
            (lambda x: x["skus"]["MI350X"]["peak_tflops"].__setitem__("fp32", 157.3), "fp32:fp16 ratio"),
            (lambda x: x["skus"]["R9700"].__setitem__("lds_per_cu_kib", 64.0), "per-CU LDS"),
            (lambda x: x["skus"]["MI300X"].__setitem__("ridge_ops_per_byte", 247), "derived ridge"),
            (lambda x: x["skus"]["AI_MAX_395"].__setitem__("measured_ceilings", []), "tool + version"),
            (lambda x: x["skus"]["R9700"].__setitem__("roofline_default_for_arch", True), "gfx1201"),
            (lambda x: x["skus"]["W7900"].__setitem__("geak_support", "supported"), "reference only"),
            (lambda x: x["skus"].__setitem__("MI300X", x["skus"].pop("MI300X")), "row order")):
        m = copy.deepcopy(d)
        if needle == "row order":       # move a gfx942 row ahead of the gfx950 ones
            m["skus"] = {"MI300X": m["skus"].pop("MI300X"), **m["skus"]}
        else:
            mutate(m)
        got = check(m)
        assert any(needle in p for p in got), (needle, got)
    # renderers: the peaks-yaml carries exactly the reachable rows, product-scoped R9700, and the
    # gfx defaults; a table renders every column
    y = render_peaks_yaml(d)
    assert "product: r9700" in y and "product: mi355x" in y and "default_for_gfx: true" in y
    assert "W7900" not in y and "AI_MAX_495" not in y and y.count("default_for_gfx: true") == 3
    t = render_table(d, ("gfx950",))
    assert t.splitlines()[2].startswith("| MI355X |") and "10000" in t, t
    # doc-block round trip on a temp file: stale -> flagged, sync -> clean
    with tempfile.TemporaryDirectory() as td:
        p = os.path.join(td, "x.md")
        with open(p, "w") as fh:
            fh.write("pre\n<!-- BEGIN GENERATED by extract_sku.py: table gfx942 -->\nold\n"
                     f"{END_MARK}\npost\n")
        assert check_docs(d, [p]) and "stale" in check_docs(d, [p])[0]
        assert sync_docs(d, [p]) == [p] and check_docs(d, [p]) == []
        assert open(p).read().startswith("pre\n") and open(p).read().endswith(f"{END_MARK}\npost\n")
    # and the real docs are in sync
    stale = check_docs(d)
    assert not stale, "\n".join(stale)
    n_docs = len(list(doc_files()))
    print(f"[extract_sku] {len(s)} SKUs; invariants clean; {n_docs} doc file(s) with generated "
          f"blocks in sync; MI300X fp16 ridge={ridge_for(s['MI300X'])} (computed, not stored)")
    print("SKU EXTRACT SELFTEST PASS")
    return 0


def main() -> None:
    argv = sys.argv[1:]
    if "--selftest" in argv:
        sys.exit(_selftest())
    d = load()
    if "--print" in argv:
        key = argv[argv.index("--print") + 1].upper()
        print(json.dumps(d["skus"].get(key, {"error": f"unknown {key}"}), indent=2))
        return
    if "--check" in argv:
        bad = check(d)
        print("\n".join(bad) if bad else "sku.json: clean")
        sys.exit(1 if bad else 0)
    if "--render" in argv:
        i = argv.index("--render")
        print(render(d, " ".join(argv[i + 1:i + 3])))
        return
    if "--check-docs" in argv:
        bad = check_docs(d)
        print("\n".join(bad) if bad else "generated doc blocks: in sync")
        sys.exit(1 if bad else 0)
    if "--sync-docs" in argv:
        for p in sync_docs(d):
            print(f"rewrote {os.path.relpath(p, REPO_ROOT)}")
        return
    if "--out" in argv or "--regen-in-place" in argv:
        print("extract_sku no longer WRITES sku.json: it is the hand-edited single source "
              "(perf_knowledge/hardware/data/sku.json). Edit it, then --check and --sync-docs.",
              file=sys.stderr)
        sys.exit(2)
    print(__doc__, file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
